data:
  data_path : "datasets/WaterRamps"
  model_path : "models/WaterRamps"
  rollout_path : "rollouts/WaterRamps"
  load_model_path: "original_model_check_point.pt" #"additive_model_check_point.pt"
  training_stats_path : "training stats/WaterRamps"

training:
  epoch: 5
  batch_size: 10
  lr: 1.0e-3 #1.0e-4
  noise: 3.0e-4
  save_interval: 2000
  eval_interval: 2000
  rollout_interval: 2000
  session_name: ""
  visualize: TRUE
  load_model_path: "2025-04-07_16_46_checkpoint_62000.pt"
  obstacle_bias: 4
  wall_bias: 4

model:
  model_version: "original_model" # "original_model" or "additive_model"
  hidden_size: 128
  n_mp_layers: 10
  window_size: 5
  max_neighbours: 20