data:
  data_path : "datasets/WaterDrop"
  model_path : "models/WaterDrop"
  training_stats_path : "training stats/WaterDrop"

training:
  epoch: 1
  batch_size: 4
  lr: 1.0e-4
  noise: 3.0e-4
  save_interval: 2000
  eval_interval: 2000
  rollout_interval: 2000
  session_name: ""

model:
  hidden_size: 128
  n_mp_layers: 10
  window_size: 5