data:
  data_path : "datasets/WaterRamps"
  model_path : "models/WaterRamps"
  training_stats_path : "training stats/WaterRamps"

training:
  epoch: 5
  batch_size: 4
  lr: 1.0e-4
  noise: 3.0e-4
  save_interval: 5000
  eval_interval: 5000
  rollout_interval: 5000
  session_name: ""
  visualize: TRUE
  load_model_path: "2025-04-04_22_09_checkpoint_140000.pt"
  obstacle_bias: 4
  wall_bias: 4

model:
  model_version: "original_model" # "original_model" or "additive_model"
  hidden_size: 128
  n_mp_layers: 10
  window_size: 5
  max_neighbours: 20